[package]
name = "modulo"
version = "0.1.0"
description = "Modulo 桌面壳"
edition = "2021"
rust-version = "1.77"

[lib]
name = "modulo_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde_json = "1"

[profile.release]
codegen-units = 1
lto = true
strip = true
